### ISSUE TITLE
Rendering is Broken

### ISSUE THREAD

**Issue by simonas-dev** [ugnelis/evil-twin-automated#1]
Rendering seems to be failing on macOS.
<img width="1101" alt="screen shot 2018-02-03 at 3 45 27 pm" src="https://user-images.githubusercontent.com/3253131/35767667-5d30a554-08f9-11e8-8433-babe56fc4648.png">

**Comment by ugnelis** [comment]
I think you are using Mac. Mac support will be checked later.

**Comment by Edvinas01** [comment]
@simonassank you should install superior OS, Linux or Win

**Comment by simonas-dev** [comment]
@Edvinas01 
![image](https://user-images.githubusercontent.com/3253131/35769399-d72909f0-0912-11e8-8b32-54afff35e993.png)

**Comment by Edvinas01** [comment]
> 
> 
> @simonassank you should install superior OS, Linux or Win

I have changed my mind, this needs to be fixed ASAP

**Comment by ugnelis** [comment]
Only Linux is supported :)

**Comment by Edvinas01** [comment]
> 
> 
> Only Linux is supported :)

Please add support for Mac
